# Generated by Django 5.0.8 on 2026-08-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrativos', '0001_initial'),
        ('usuarios', '0002_usuario_desativado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='preferencias',
            field=models.ManyToManyField(blank=True, related_name='usuarios_interessados', to='atrativos.categoria'),
        ),
    ]
