# Generated by Django 5.0.8 on 2026-08-13 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrativos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtrativoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='atrativos/')),
                ('imagem_capa', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atrativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='atrativos.atrativo')),
            ],
            options={
                'verbose_name': 'Imagem do Atrativo',
                'verbose_name_plural': 'Imagens dos Atrativos',
                'ordering': ['-imagem_capa', '-id'],
            },
        ),
    ]
