# Generated by Django 5.0.8 on 2026-08-13 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atrativos', '0002_atrativoimagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RotaAtrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('atrativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='atrativos.atrativo')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='rotas.rota')),
            ],
            options={
                'verbose_name': 'Atrativo do Roteiro',
                'verbose_name_plural': 'Atrativos dos Roteiros',
                'ordering': ['ordem'],
                'unique_together': {('rota', 'atrativo')},
            },
        ),
    ]
